default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "root"
  host: mysql

development:
  <<: *default
  database: dev
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
test:
  <<: *default
  database: dev

production:
  <<: *default
  database: dev
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>